export const Colony: { name: string }[] = [
  { name: "1ro de Mayo" },
  { name: "20 de Noviembre" },
  { name: "5 de Julio" },
  { name: "Aire Libre (Kilómetro 15)" },
  { name: "Altamira" },
  { name: "Alto Lucero Centro" },
  { name: "Alto de San Lorenzo" },
  { name: "Ampliación Azteca" },
  { name: "Anáhuac" },
  { name: "Arboleda" },
  { name: "Azteca" },
  { name: "Baltazar" },
  { name: "Banco del Calichar" },
  { name: "Banderas" },
  { name: "Barra Norte" },
  { name: "Benito Juárez" },
  { name: "Boca del Monte" },
  { name: "Buena Vista" },
  { name: "Buenos Aires" },
  { name: "CTM" },
  { name: "Cabo Alto" },
  { name: "Cabo Rojo" },
  { name: "Campo Real" },
  { name: "Cañada Rica" },
  { name: "Ceiba Rica" },
  { name: "Cerro de Tumilco" },
  { name: "Chacoaco" },
  { name: "Chalahuite" },
  { name: "Chiconcoa" },
  { name: "Chijolar" },
  { name: "Chomotla" },
  { name: "Cobos" },
  { name: "Comején" },
  { name: "Concepción" },
  { name: "Cruz Naranjos" },
  { name: "Dante Delgado" },
  { name: "El Angosto" },
  { name: "El Capullo" },
  { name: "El Coyol" },
  { name: "El Esfuerzo" },
  { name: "El Jobo" },
  { name: "El Lindero" },
  { name: "El Muro" },
  { name: "El Paraíso" },
  { name: "El Progreso" },
  { name: "El Vergel" },
  { name: "Emiliano Zapata" },
  { name: "Escudero" },
  { name: "Esperanza Azcon" },
  { name: "Fernando Gutiérrez Barrios" },
  { name: "Francisco I. Madero" },
  { name: "Frijolillo" },
  { name: "Géminis INFONAVIT" },
  { name: "Higo de la Esperanza" },
  { name: "Higueral" },
  { name: "Héroe de Nacozari (Arroyo de San Lorenzo)" },
  { name: "Héroes de Chapultepec (El Tamarindo)" },
  { name: "INFONAVIT Castillo" },
  { name: "INFONAVIT Puerto Pesquero" },
  { name: "Juan Zumaya (El Remate)" },
  { name: "Juana Moza" },
  { name: "Juárez" },
  { name: "La Calzada" },
  { name: "La Camelia" },
  { name: "La Ceiba" },
  { name: "La Laja de Coloman" },
  { name: "La Laja de Zapote Bueno" },
  { name: "La Mata" },
  { name: "La Unión" },
  { name: "La Victoria" },
  { name: "Laja del Tubo" },
  { name: "Las Animas" },
  { name: "Las Palmas" },
  { name: "Las Pasas" },
  { name: "Linda Vista" },
  { name: "Loma Alta" },
  { name: "Los Pinos" },
  { name: "Lázaro Cárdenas" },
  { name: "Macuiltépetl" },
  { name: "Manlio Fabio Altamirano" },
  { name: "Mexicana Miguel Alemán" },
  { name: "Miguel Hidalgo" },
  { name: "Miramar (La Antigua)" },
  { name: "Monte Horeb" },
  { name: "Monte Morelos" },
  { name: "Montes de Armenia" },
  { name: "Murillo Vidal" },
  { name: "Nalúa" },
  { name: "Niños Héroes" },
  { name: "Nuevo Sol" },
  { name: "Ojite" },
  { name: "Ojite Rancho Nuevo" },
  { name: "Olímpica" },
  { name: "Otatal" },
  { name: "Palma de Morelos" },
  { name: "Parque industrial Corredor Industrial" },
  { name: "Países Bajos (Kilómetro 8)" },
  { name: "Peña Alta" },
  { name: "Peña de Afuera" },
  { name: "Playa Azul" },
  { name: "Playa Emiliano Zapata" },
  { name: "Praxedis Guerrero (Kilómetro 18)" },
  { name: "Puente Don Diego" },
  { name: "Rafael Hernández Ochoa" },
  { name: "Rancho Viejo" },
  { name: "Rodríguez Alcaine" },
  { name: "Sabanillas" },
  { name: "Salto de La Reforma" },
  { name: "San José el Grande" },
  { name: "Santiago de la Peña" },
  { name: "Tampamachoco" },
  { name: "Tampiquillo" },
  { name: "Tebanco" },
  { name: "Tierra Blanca" },
  { name: "Tronconal" },
  { name: "Tronconal de Herrera Beltrán" },
  { name: "Túxpam de Rodríguez Cano Centro" },
  { name: "Unidad habitacional Franco Cruz Hernández" },
  { name: "Unidad habitacional Jesús Reyes Heroles" },
  { name: "Villa Mar" },
  { name: "Zapotal Zaragoza" },
  { name: "Zapotalillo" },
  { name: "Zapote Domingo" },
  { name: "Álvarez" },
];
